pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: Build and Push Image
    inputs:
      containerRegistry: '$(CONTAINER_REGISTRY_SERVICE_CONN)'
      repository: 'pre-commit-terraform'
      command: "buildAndPush"
      tags: "0.15.3"
