pool:
  vmImage: ubuntu-latest

parameters:
  - name: TERRAFORM_VERSION
    displayName: "Terraform version"
    type: string
    values:
      - '0.15.3'
    default: patch

steps:
  - task: Docker@2
    inputs:
      containerRegistry: '$(CONTAINER_REGISTRY_SERVICE_CONN)'
      repository: '$(CONTAINER_REGISTRY_NAME)'
      command: 'buildAndPush'
      Dockerfile: '.Dockerfile'
      arguments: TERRAFORM_VERSION=$(TERRAFORM_VERSION)
      tags: '$(TERRAFORM_VERSION)'
